name: Build and push image
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build images
        run: docker build -t kvesten/urmat:latest .
      - name: push
        run: |
          docker login --username kvesten -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push kvesten/urmat:latest
